### ISSUE TITLE
Support Ruby 3.0, blocking DSI test fails

### ISSUE THREAD

**Issue by jwillemsen** [RemedyIT/r2corba#41]
Coming from the CI test build https://github.com/RemedyIT/r2corba/pull/32

```
2020-12-22T16:02:12.8606318Z ##### running test DSI
2020-12-22T16:02:12.8606596Z 
2020-12-22T16:02:13.1135223Z server.rb:88: [BUG] Segmentation fault at 0x0000000000000034
2020-12-22T16:02:13.1137097Z ruby 3.0.0rc1 (2020-12-20 master 8680ae9cbd) [x86_64-linux]
2020-12-22T16:02:13.1137651Z 
2020-12-22T16:02:13.1139049Z -- Control frame information -----------------------------------------------
2020-12-22T16:02:13.1139852Z c:0004 p:---- s:0020 e:000019 CFUNC  :_default_POA
2020-12-22T16:02:13.1140432Z c:0003 p:---- s:0017 e:000016 CFUNC  :_this
2020-12-22T16:02:13.1140945Z c:0002 p:0158 s:0013 E:0021f8 EVAL   server.rb:88 [FINISH]
2020-12-22T16:02:13.1141375Z c:0001 p:0000 s:0003 E:001c60 (none) [FINISH]
2020-12-22T16:02:13.1141632Z 
```

**Comment by jwillemsen** [comment]
Still happens

```
##### running test DSI

server.rb:88: [BUG] Segmentation fault at 0x0000000000000034
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0020 e:000019 CFUNC  :_default_POA
c:0003 p:---- s:0017 e:000016 CFUNC  :_this
c:0002 p:0158 s:0013 E:000048 EVAL   server.rb:88 [FINISH]
c:0001 p:0000 s:0003 E:001f80 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
server.rb:88:in `<main>'
server.rb:88:in `_this'
server.rb:88:in `_default_POA'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f2c2ec8cc35 RBP: 0x0000000000000034 RSP: 0x00007ffcfb84c1d0
 RAX: 0x0000000000000000 RBX: 0x0000000000019361 RCX: 0x00007f2c2ec8cc10
 RDX: 0x0000000000000000 RDI: 0x000055bf269dc868 RSI: 0x0000000000000000
  R8: 0x000055bf269dc868  R9: 0x0000000000000000 R10: 0x0000000000000000
 R11: 0x0000000000000000 R12: 0x000055bf2637cc80 R13: 0x0000000000000000
 R14: 0x000055bf269e4978 R15: 0x000055bf269a3720 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(rb_print_backtrace+0x11) [0x7f2c33844303] vm_dump.c:758
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(rb_vm_bugreport) vm_dump.c:998
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(rb_bug_for_fatal_signal+0xf4) [0x7f2c3364e084] error.c:786
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(sigsegv+0x4d) [0x7f2c3379b1dd] signal.c:960
/lib/x86_64-linux-gnu/libc.so.6(0x7f2c333c2210) [0x7f2c333c2210]
/home/runner/work/r2corba/r2corba/ext/librpoa.so(_ZL25r2tao_Servant_default_POAm+0x25) [0x7f2c2ec8cc35]
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(vm_cfp_consistent_p+0x0) [0x7f2c33833e66] vm_eval.c:135
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(vm_call0_cfunc_with_frame) vm_eval.c:137
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(vm_call0_cfunc) vm_eval.c:149
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(vm_call0_body) vm_eval.c:180
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(rb_funcallv+0x19c) [0x7f2c3383710c] vm_eval.c:72
/home/runner/work/r2corba/r2corba/ext/librpoa.so(0x13d98) [0x7f2c2ec8cd98]
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(vm_call_cfunc_with_frame+0x11b) [0x7f2c3381c1bb] vm_insnhelper.c:2926
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(vm_call_method_each_type+0x79) [0x7f2c338302b9] vm_insnhelper.c:3416
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(vm_call_method+0xb4) [0x7f2c33830994] vm_insnhelper.c:3534
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(vm_sendish+0xe) [0x7f2c33829297] vm_insnhelper.c:4527
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(vm_exec_core) insns.def:789
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(rb_vm_exec+0xa54) [0x7f2c3382f744] vm.c:2172
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(rb_ec_exec_node+0xed) [0x7f2c33652f9d] eval.c:317
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0(ruby_run_node+0x5a) [0x7f2c33658efa] eval.c:375
7f2c33332000-7f2c33335000 r--p 00000000 08:11 3442                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f2c33335000-7f2c33339000 r-xp 00003000 08:11 3442                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f2c33339000-7f2c3333a000 r--p 00007000 08:11 3442                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f2c3333a000-7f2c3333b000 ---p 00008000 08:11 3442                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f2c3333b000-7f2c3333c000 r--p 00008000 08:11 3442                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f2c3333c000-7f2c3333d000 rw-p 00009000 08:11 3442                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f2c3333d000-7f2c33344000 r--p 00000000 08:11 3440                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f2c33344000-7f2c33355000 r-xp 00007000 08:11 3440                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f2c33355000-7f2c3335a000 r--p 00018000 08:11 3440                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f2c3335a000-7f2c3335b000 r--p 0001c000 08:11 3440                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f2c3335b000-7f2c3335c000 rw-p 0001d000 08:11 3440                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f2c3335c000-7f2c33360000 rw-p 00000000 00:00 0 
7f2c33360000-7f2c33362000 r--p 00000000 08:11 4548                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f2c33362000-7f2c33373000 r-xp 00002000 08:11 4548                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f2c33373000-7f2c33379000 r--p 00013000 08:11 4548                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f2c33379000-7f2c3337a000 ---p 00019000 08:11 4548                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f2c3337a000-7f2c3337b000 r--p 00019000 08:11 4548                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f2c3337b000-7f2c3337c000 rw-p 0001a000 08:11 4548                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f2c3337c000-7f2c333a1000 r--p 00000000 08:11 3427                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f2c333a1000-7f2c33519000 r-xp 00025000 08:11 3427                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f2c33519000-7f2c33563000 r--p 0019d000 08:11 3427                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f2c33563000-7f2c33564000 ---p 001e7000 08:11 3427                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f2c33564000-7f2c33567000 r--p 001e7000 08:11 3427                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f2c33567000-7f2c3356a000 rw-p 001ea000 08:11 3427                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f2c3356a000-7f2c3356e000 rw-p 00000000 00:00 0 
7f2c33572000-7f2c33573000 r--p 00000000 08:11 5950817                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/x86_64-linux/enc/encdb.so
7f2c33573000-7f2c33574000 r-xp 00001000 08:11 5950817                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/x86_64-linux/enc/encdb.so
7f2c33574000-7f2c33575000 r--p 00002000 08:11 5950817                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/x86_64-linux/enc/encdb.so
7f2c33575000-7f2c33576000 r--p 00002000 08:11 5950817                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/x86_64-linux/enc/encdb.so
7f2c33576000-7f2c33577000 rw-p 00003000 08:11 5950817                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/x86_64-linux/enc/encdb.so
7f2c33577000-7f2c3357e000 r--s 00000000 08:11 3722                       /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f2c3357e000-7f2c335ae000 r--p 00000000 08:11 5173047                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0.2
7f2c335ae000-7f2c33852000 r-xp 00030000 08:11 5173047                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0.2
7f2c33852000-7f2c33958000 r--p 002d4000 08:11 5173047                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0.2
7f2c33958000-7f2c3395f000 r--p 003d9000 08:11 5173047                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0.2
7f2c3395f000-7f2c33962000 rw-p 003e0000 08:11 5173047                    /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0.2
7f2c33962000-7f2c33975000 rw-p 00000000 00:00 0 
7f2c33975000-7f2c33976000 r--p 00000000 08:11 3423                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f2c33976000-7f2c33999000 r-xp 00001000 08:11 3423                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f2c33999000-7f2c339a1000 r--p 00024000 08:11 3423                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f2c339a2000-7f2c339a3000 r--p 0002c000 08:11 3423                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f2c339a3000-7f2c339a4000 rw-p 0002d000 08:11 3423                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f2c339a4000-7f2c339a5000 rw-p 00000000 00:00 0 
7ffcfa84f000-7ffcfb84e000 rw-p 00000000 00:00 0                          [stack]
7ffcfb99d000-7ffcfb9a1000 r--p 00000000 00:00 0                          [vvar]
7ffcfb9a1000-7ffcfb9a3000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


ERROR: could not find file 'server.ior'
client.rb:59:in `<main>': undefined method `echo' for nil:NilClass (NoMethodError)
ERROR: client.rb returned: 1
E
===============================================================================
Error: test_DSI(TestFinder::TestRunner): RuntimeError: Execution of test DSI failed with exitstatus 1
(eval):7:in `test_DSI'
===============================================================================
```
